### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by eransc**
The version of allure-js-commons bundled into this package is 1.0.2 so the runtime.js is missing some capabilities as compared to the one implemented in version 1.1.4

Missing methods: addLabel, addArgument, addEnvironment, description and more

Bundling allure-ja-commons version 1.1.4 into the current jasmine-allure-plugin solve the issue

### CODE REVIEW

**Comment by eransc** [comment]
@ctapobep - please approve the PR

**Comment by ctapobep** [comment]
Oops, didn't notice this. Need to test that.

**Comment by ctapobep** [comment]
@eransc could you please update your commit message and mention why this update is necessary and what new features you're trying to introduce?

**Comment by eransc** [comment]
@ctapobep - i have updated the commit message

**Comment by eransc** [comment]
@ctapobep - Can you check ?

**Comment by ctapobep** [comment]
Checked. I'm ok to merge it, but please create a PR to the official plugin repo: https://github.com/allure-framework/allure-jasmine-plugin Don't forget to rebase on the last commit in that repo.

Also, your commit message still doesn't shed light on what exactly you're updating the dependency for - just general abstract wording..

**Pull request merged**
